import { z } from 'zod';

// Public RacePic manifests are served as static CDN JSON; only downloads use the API.
// Manifests are generated by api/src/racepic/publish.ts in the backend repository. Browsing a
// gallery therefore does not invoke Lambda or RDS; only download authorization uses the API.

const cdnBaseUrl = (import.meta.env.VITE_RACEPIC_CDN_BASE_URL || '').replace(/\/$/, '');
const configuredEventApiBaseUrl = (import.meta.env.VITE_EVENT_API_BASE_URL || '').replace(/\/$/, '');
const eventApiBaseUrl = import.meta.env.DEV && configuredEventApiBaseUrl ? '/event-api' : configuredEventApiBaseUrl;

export const isRacePicPublicConfigured = (): boolean => cdnBaseUrl.length > 0;

class RacePicPublicError extends Error {
  constructor(public readonly status: number) {
    super(`HTTP_${status}`);
  }
}
export { RacePicPublicError };

async function fetchManifest<T>(path: string, schema: z.ZodTypeAny): Promise<T> {
  if (!isRacePicPublicConfigured()) throw new RacePicPublicError(0);
  const response = await fetch(`${cdnBaseUrl}${path}`, { cache: 'no-store' });
  if (!response.ok) throw new RacePicPublicError(response.status);
  const parsed = schema.safeParse(await response.json());
  if (!parsed.success) throw new RacePicPublicError(502);
  return parsed.data as T;
}

export type RacePicEventSummary = { eventId: string; slug: string; title: string };
const eventSummarySchema = z.object({ eventId: z.string().uuid(), slug: z.string().min(1), title: z.string() });

export const fetchPublishedEvents = () => fetchManifest<RacePicEventSummary[]>('/manifests/events.json', z.array(eventSummarySchema));

export type RacePicParticipant = {
  participantKey: string;
  startNumber: string;
  className: string;
  vehicleType: string;
  displayName: string;
  make: string | null;
  model: string | null;
  imageCount: number;
  coverThumbUrl: string;
};
const participantSchema = z.object({
  participantKey: z.string().min(1), startNumber: z.string(), className: z.string(), vehicleType: z.string(), displayName: z.string(),
  make: z.string().nullable(), model: z.string().nullable(), imageCount: z.number().int().nonnegative(), coverThumbUrl: z.string()
});

export type RacePicImage = {
  imageId: string;
  thumbUrl: string;
  previewUrl: string;
  width: number | null;
  height: number | null;
  title: string | null;
  description: string | null;
  tags: string[];
  camera: { make?: string | null; model?: string | null } | null;
  capturedAt: string | null;
  createdAt: string;
  photographer: { displayName: string; website: string | null; slug: string | null };
  license: { code: string; title: Record<string, string>; attributionRequired: boolean; attributionTemplate: string | null };
};
const imageSchema = z.object({
  imageId: z.string().uuid(), thumbUrl: z.string(), previewUrl: z.string(), width: z.number().int().nullable(), height: z.number().int().nullable(),
  title: z.string().nullable(), description: z.string().nullable(), tags: z.array(z.string()),
  camera: z.object({ make: z.string().nullable().optional(), model: z.string().nullable().optional() }).passthrough().nullable(),
  capturedAt: z.string().nullable(), createdAt: z.string(),
  photographer: z.object({ displayName: z.string(), website: z.string().nullable(), slug: z.string().nullable() }),
  license: z.object({ code: z.string(), title: z.record(z.string()), attributionRequired: z.boolean(), attributionTemplate: z.string().nullable() })
});

export type RacePicParticipantGallery = { participant: RacePicParticipant; images: RacePicImage[] };
const participantGallerySchema = z.object({ participant: participantSchema, images: z.array(imageSchema) });

export const fetchParticipantGallery = (slug: string, participantKey: string) =>
  fetchManifest<RacePicParticipantGallery>(`/manifests/${encodeURIComponent(slug)}/p/${encodeURIComponent(participantKey)}.json`, participantGallerySchema);

// --- Paket 12: öffentliches Fotografenprofil --------------------------------------------------

export type RacePicPhotographerImage = {
  imageId: string;
  thumbUrl: string;
  previewUrl: string;
  eventSlug: string;
  eventTitle: string;
  capturedAt: string | null;
};

export type RacePicPhotographerProfile = {
  photographerId: string;
  slug: string;
  displayName: string;
  copyrightLine: string | null;
  website: string | null;
  social: Record<string, string>;
  imageCount: number;
  images: RacePicPhotographerImage[];
};
const photographerProfileSchema = z.object({
  photographerId: z.string().uuid(), slug: z.string(), displayName: z.string(), copyrightLine: z.string().nullable(), website: z.string().nullable(),
  social: z.record(z.string()), imageCount: z.number().int().nonnegative(),
  images: z.array(z.object({ imageId: z.string().uuid(), thumbUrl: z.string(), previewUrl: z.string(), eventSlug: z.string(), eventTitle: z.string(), capturedAt: z.string().nullable() }))
});

export const fetchPhotographerProfile = (slug: string) =>
  fetchManifest<RacePicPhotographerProfile>(`/manifests/photographers/${encodeURIComponent(slug)}.json`, photographerProfileSchema);

// --- Paket 17: globale Discover-/Suchindex-Manifeste (Landingpage) -----------------------------

export type RacePicDiscoverImage = {
  imageId: string;
  thumbUrl: string;
  previewUrl: string;
  eventSlug: string;
  eventTitle: string;
  capturedAt: string | null;
  createdAt: string;
};
const discoverImageSchema = z.object({
  imageId: z.string().uuid(), thumbUrl: z.string(), previewUrl: z.string(), eventSlug: z.string(), eventTitle: z.string(),
  capturedAt: z.string().nullable(), createdAt: z.string()
});

export const fetchDiscoverFeed = () => fetchManifest<RacePicDiscoverImage[]>('/manifests/discover.json', z.array(discoverImageSchema));

export type RacePicDiscoverIndex = { total: number; pageCount: number; pageSize: number };
const discoverIndexSchema = z.object({ total: z.number().int().nonnegative(), pageCount: z.number().int().nonnegative(), pageSize: z.number().int().positive() });
export const fetchDiscoverIndex = () => fetchManifest<RacePicDiscoverIndex>('/manifests/discover-index.json', discoverIndexSchema);
export const fetchDiscoverPage = (page: number) =>
  fetchManifest<RacePicDiscoverImage[]>(`/manifests/discover-pages/${Math.max(1, Math.trunc(page))}.json`, z.array(discoverImageSchema));

export type RacePicImageDetail = {
  image: RacePicImage;
  eventSlug: string;
  eventTitle: string;
  participants: RacePicParticipant[];
  relatedImages: RacePicImage[];
};
const imageDetailSchema = z.object({
  image: imageSchema, eventSlug: z.string(), eventTitle: z.string(), participants: z.array(participantSchema), relatedImages: z.array(imageSchema)
});
export const fetchImageDetail = (eventSlug: string, imageId: string) =>
  fetchManifest<RacePicImageDetail>(`/manifests/${encodeURIComponent(eventSlug)}/i/${encodeURIComponent(imageId)}.json`, imageDetailSchema);

export type RacePicSearchIndexEntry = {
  participantKey: string;
  eventSlug: string;
  eventTitle: string;
  startNumber: string;
  displayName: string;
  make: string | null;
  model: string | null;
  className: string;
};
const searchIndexEntrySchema = z.object({
  participantKey: z.string(), eventSlug: z.string(), eventTitle: z.string(), startNumber: z.string(), displayName: z.string(),
  make: z.string().nullable(), model: z.string().nullable(), className: z.string()
});

export const fetchSearchIndex = () => fetchManifest<RacePicSearchIndexEntry[]>('/manifests/search-index.json', z.array(searchIndexEntrySchema));

/** Convert a validated relative manifest asset path to an absolute CDN URL. */
export const toCdnUrl = (relativePath: string): string => {
  if (!/^\/(public|manifests)\/[A-Za-z0-9._~!$&'()*+,;=:@%/-]+$/.test(relativePath) || relativePath.includes('..')) {
    throw new RacePicPublicError(400);
  }
  return `${cdnBaseUrl}${relativePath}`;
};

export type DownloadVariant = 'small' | 'medium' | 'large' | 'original';

export type DownloadResult = {
  url: string;
  expiresAt: string;
  attribution: {
    photographerName: string;
    copyrightLine: string | null;
    licenseCode: string;
    licenseTitle: Record<string, string>;
    attributionRequired: boolean;
    attributionTemplate: string | null;
  };
};
const downloadResultSchema = z.object({
  url: z.string().url(),
  expiresAt: z.string(),
  attribution: z.object({
    photographerName: z.string(), copyrightLine: z.string().nullable(), licenseCode: z.string(),
    licenseTitle: z.record(z.string()), attributionRequired: z.boolean(), attributionTemplate: z.string().nullable()
  })
});

export const requestDownload = async (imageId: string, variant: DownloadVariant): Promise<DownloadResult> => {
  if (!configuredEventApiBaseUrl) throw new RacePicPublicError(0);
  const response = await fetch(`${eventApiBaseUrl}/public/racepic/images/${encodeURIComponent(imageId)}/download`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ variant })
  });
  const payload = await response.json().catch(() => null);
  if (!response.ok || !payload) throw new RacePicPublicError(response.status);
  const parsed = downloadResultSchema.safeParse(payload);
  if (!parsed.success) throw new RacePicPublicError(502);
  return parsed.data as DownloadResult;
};
